title: "Code & Crate"
timezone: IST
email: codeandcrate@gmail.com
baseurl: ""
url: https://codeandcrate.netlify.app/
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-H4T1JXZ3VN

# Authors
authors:
  sal:
    name: Code
    display_name: Sal
    avatar: 'assets/images/sal.png'
    twitter: https://x.com/codeandcrate
    description: "Tech tinkerer and creator behind Code & Crate."
  john:
    name: Code & Crate
    display_name: Codeandcrate
    avatar: 'assets/images/john.png'
    twitter: https://x.com/codeandcrate
    description: "Passionate about coding, gadgets, and all things DIY."

# Social
social:
  pinterest: https://in.pinterest.com/codeandcrate
  twitter: https://x.com/codeandcrate

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
